Добавляет все виды фильтров и debounce
htmlacademy-javascript/520531-keksobooking-22 pull request #11
Opened 2021-03-23 19:02 UTC by pavelvorobev

фух :)

2021-03-24 09:23 UTC, nikkypizza requested changes

2021-03-24 10:55 UTC, nikkypizza commented on js/submit.js
>      const formData = new FormData(evt.target);
Функция **setOfferFormSubmit** по сути является лишней оберткой, от нее можно избавиться.

2021-03-25 08:25 UTC, nikkypizza approved these changes
Четко!

2021-03-25 08:25 UTC, nikkypizza commented on js/filter.js
> +const filterOffers = debounce((offers) => {
Тут есть узкое место в плане оптимизации.
Все вспомогательные функции фильтрации объявляются заново при каждой фильтрации. Давай вынесем их за пределы **filterOffers**, таким образом тут будут только вызовы и перерисовка:
```js
const filterOffers = debounce((offers) => {
  const filteredOffers = offers.filter(filterOffersByType)
    .filter(filterOffersByPrice)
    .filter(filterOffersByRooms)
    .filter(filterOffersByGuests)
    .filter(filterOffersByFeatures);

  regularPinsArr.forEach((marker) => marker.remove());
  getPins(filteredOffers);
}, RERENDER_DELAY )
```

2021-03-25 08:25 UTC, nikkypizza commented on js/filter.js
> +  };
Повтор можно вынести в отдельную функцию, как [писал ранее](https://github.com/htmlacademy-javascript/520531-keksobooking-22/pull/11#discussion_r600285820):
 ```js
 const fn = (offer, offerField, pageField) => {
  if (pageField.value === offerField || pageField.value === 'any') {
    return offer;
  }
};

const filterOffersByRooms = (offer) => fn(offer, offer.offer.rooms.toString(), mapFiltersForm['housing-rooms']);
const filterOffersByType = (offer) => fn(offer, offer.offer.type, mapFiltersForm['housing-type']);
//...
 ```
 название за тобой

2021-03-25 08:28 UTC, merged

2021-03-26 18:19 UTC, pavelvorobev commented on js/filter.js
> +  });
Неочень понимаю логику отрицаний в данной функции. Без них фильтрация по преимуществам продолжает верно работать, а вот по другим полям ломается